server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # This is required for React Router to work correctly with Nginx
        try_files $uri $uri/ /index.html;
    }
}
